version: '3.7'
services:   
  web:
    image: nginx:stable-alpine3.17-slim
    container_name: web
    depends_on:
      - php1
      - php2
      - php3
    volumes:
      - ./data/web:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - load-balancer-net

  php1:
    build: docker/php8.3-fpm
    container_name: php1
    hostname: php1.net
    depends_on:
      - redis
    volumes:
      - ./data/web:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - load-balancer-net

  php2:
    build: docker/php8.3-fpm
    container_name: php2
    hostname: php2.net
    depends_on:
      - redis
    volumes:
      - ./data/web:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - load-balancer-net

  php3:
    build: docker/php8.3-fpm
    container_name: php3
    hostname: php3.net
    depends_on:
      - redis
    volumes:
      - ./data/web:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - load-balancer-net

  redis:
    image: redis/redis-stack
    container_name: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 8082:8001
    networks:
      - load-balancer-net

networks:
  load-balancer-net:
    name: load-balancer-network
